#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — Tag Scan native OCR (issue #22): get the Vision OCR dev client
# built and running on a real iPhone, signed with a free Apple ID (no paid
# Apple Developer Program membership needed — see docs/adr and the
# conversation this script came from for why that's genuinely sufficient
# for local device testing).
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

# This script lives at apps/mobile/scripts/ — every command below assumes
# apps/mobile as the working directory.
cd "$(dirname "$0")/.."

banner "Tag Scan: Vision OCR dev client setup"

# ── 1. Xcode ────────────────────────────────────────────────────────────
stage "Xcode + command line tools"
say "Expo SDK 54 needs Xcode 16.1 or newer."
if command -v xcodebuild >/dev/null 2>&1; then
  XCODE_VERSION=$(xcodebuild -version 2>/dev/null | head -n1 || true)
  say "Found: ${XCODE_VERSION:-unknown version}"
else
  warn "xcodebuild not found."
  step "Install Xcode from the Mac App Store, then open it once and let it finish its first-launch component install."
  pause "Press Enter once Xcode is installed and has finished its first launch."
fi
say "If this is the first time running Xcode's command line tools, macOS may still need you to accept its license."
step "Run 'sudo xcodebuild -license' in a separate terminal if prompted, and accept it."
pause "Press Enter once Xcode is installed, licensed, and ready."

# ── 2. CocoaPods ────────────────────────────────────────────────────────
stage "CocoaPods"
if command -v pod >/dev/null 2>&1; then
  say "Found: $(pod --version 2>/dev/null || echo 'installed')"
else
  warn "CocoaPods not found."
  step "Install it: sudo gem install cocoapods   (or: brew install cocoapods)"
  pause "Press Enter once 'pod --version' works in a terminal."
fi

# ── 3. EAS project setup — OPTIONAL for today's goal ────────────────────
# Getting the app running on your own phone via Xcode (stages 4-7) needs
# NONE of this — Xcode's own automatic signing with your free Apple ID
# handles build+sign+install in one Run click, no EAS involvement at all.
# EAS only starts to matter once you want `eas build` itself to produce a
# signed .ipa (e.g. to share a build without opening Xcode, or later once
# you have a paid Apple Developer account for TestFlight/App Store). Doing
# that with a *free* personal-team certificate additionally requires
# manually exporting that certificate from Keychain Access into a
# credentials.json — fiddly, and not needed just to test on your own phone.
stage "EAS project setup (optional — skip if you only want Xcode today)"
say "You said you can run 'eas build', so this sets that up too — but it's"
say "not required for stages 4-7 below, which get the app on your phone"
say "without any of this."
if confirm "Skip EAS setup for now and go straight to building via Xcode?"; then
  note "Skipped. Re-run this script later (or just 'eas login' / 'eas build:configure'"
  note "by hand) whenever you actually want an eas-build-produced .ipa."
else
  if npx --yes eas-cli whoami >/dev/null 2>&1; then
    say "Already logged in as: $(npx --yes eas-cli whoami 2>/dev/null)"
  else
    step "Running 'eas login' — sign up for a free Expo account if you don't have one."
    npx --yes eas-cli login
  fi
  if grep -q '"eas"' app.json 2>/dev/null; then
    say "app.json already has an eas project link — skipping."
  else
    say "This creates eas.json and adds an extra.eas.projectId to app.json."
    confirm "Run 'eas build:configure' now?" && npx --yes eas-cli build:configure || warn "skipped — run 'eas build:configure' by hand later."
  fi
  note "Not configuring credentialsSource/credentials.json here — that's the"
  note "fiddly manual-export step mentioned above. Cross that bridge only if"
  note "you actually reach for 'eas build --local' later; Xcode's Run button"
  note "(stage 6) doesn't need it."
fi

# ── 4. Generate the native iOS project ─────────────────────────────────
stage "Generate the native iOS project (expo prebuild)"
say "apps/mobile has no ios/ directory yet — this is the first native module"
say "(modules/tag-ocr) the project needs. Prebuild generates it from app.json"
say "plus every installed Expo config plugin."
if [[ -d ios ]]; then
  say "ios/ already exists."
  confirm "Regenerate it with --clean anyway? (safe — it's fully derived from app.json/plugins)" && npx expo prebuild --clean
else
  confirm "Run 'npx expo prebuild --clean' now?" && npx expo prebuild --clean || warn "skipped — run it by hand before continuing."
fi

# ── 5. Install CocoaPods dependencies ──────────────────────────────────
stage "Install CocoaPods dependencies"
say "Prebuild usually runs this automatically, but running it again is harmless."
if [[ -d ios ]]; then
  (cd ios && npx pod-install) || warn "pod-install failed — check the Xcode/CocoaPods versions above."
else
  warn "ios/ still doesn't exist — go back to stage 4."
fi

# ── 6. Sign and run from Xcode (free personal-team signing) ────────────
stage "Sign with your free Apple ID and run on your iPhone"
say "This is the one stage that has to happen in Xcode's UI, not this script."
WORKSPACE=$(ls ios/*.xcworkspace 2>/dev/null | head -n1 || true)
if [[ -n "$WORKSPACE" ]]; then
  step "Opening $WORKSPACE in Xcode..."
  open "$WORKSPACE"
else
  warn "No .xcworkspace found under ios/ — check stage 4/5 completed."
fi
step "Connect your iPhone to the Mac with a cable."
step "In Xcode's toolbar, select your iPhone as the run destination (not a Simulator)."
step "Click the blue project icon in the left sidebar → select the app target → 'Signing & Capabilities' tab."
step "Check 'Automatically manage signing'. For 'Team', pick your own Apple ID — Xcode lists it as \"<your name> (Personal Team)\" if you've never paid for the Developer Program."
step "Press the ▶ Run button. First build takes a while — this compiles the whole native project, including the Vision OCR module."
note "If Xcode reports a signing/provisioning error, it usually means the Team picker above wasn't set — go back and set it."
pause "Press Enter once Xcode says it installed and launched the app on your phone."

# ── 7. Trust the developer certificate on the phone ────────────────────
stage "Trust the developer certificate on your iPhone"
say "A free-signed app won't open the first time until you trust it."
step "On your iPhone: Settings → General → VPN & Device Management."
step "Tap your Apple ID under 'Developer App', then tap 'Trust'."
step "Return to the Home Screen and open the app again — it should launch this time."
pause "Press Enter once the app opens successfully on your phone."
note "Free signing expires after 7 days. When it does, re-run stage 6 (Xcode Run) —"
note "or 'eas build --platform ios --profile development --local' + reinstall the"
note ".ipa — to re-sign it. Re-running this whole script is safe any time."

finish

say "Start the JS bundler and connect the dev client you just installed:"
say "  npx expo start --dev-client"
say ""
say "On your phone, open the app (it's now a custom dev client, not Expo Go)"
say "and it should connect to Metro automatically on the same Wi-Fi network."
say "From the Dashboard, tap 'Scan a tag' to reach the real camera capture flow"
say "and test OCR against an actual nursery tag."
