import type { Property, PropertyInput, PropertyRow } from '@plant-app/domain'
import { propertyFromRow } from '@plant-app/domain'
import type { SupabaseClient } from '@supabase/supabase-js'
import * as Crypto from 'expo-crypto'
import type { PickedPhoto } from '../lib/pickPhoto'

type Row = Record<string, unknown>
type DbResult<T> = { data: T; error: { message: string; code?: string } | null }

/** The slice of a Postgrest filter builder the repository actually calls. */
interface PropertiesQuery extends PromiseLike<DbResult<unknown>> {
  select(columns?: string): PropertiesQuery
  eq(column: string, value: string): PropertiesQuery
  maybeSingle(): PropertiesQuery
  single(): PropertiesQuery
}

/** The narrow shape of a Supabase client this app needs — mirrors apps/web's PropertiesDbClient pattern, trimmed to what the Map screen reads and what base-map setup (#15) writes and deletes. Still no `functions`: creating a Property from an *address* stays web-only, since that path needs the `search-addresses`/`create-property` Edge Functions. */
export interface PropertiesDbClient {
  from(table: 'properties'): {
    select(columns?: string): PropertiesQuery
    insert(values: Row): PropertiesQuery
    update(values: Row): PropertiesQuery
    delete(): PropertiesQuery
  }
  storage: {
    from(bucket: string): {
      upload(
        path: string,
        body: ArrayBuffer,
        options?: { contentType?: string },
      ): Promise<{ data: { path: string } | null; error: { message: string } | null }>
      createSignedUrl(
        path: string,
        expiresIn: number,
      ): Promise<{ data: { signedUrl: string } | null; error: { message: string } | null }>
    }
  }
  auth: {
    getUser(): Promise<{
      data: { user: { id: string } | null }
      error: { message: string } | null
    }>
  }
}

/** See apps/web's `asPlantsDbClient` for why this cast exists. */
export function asPropertiesDbClient(client: SupabaseClient): PropertiesDbClient {
  return client as unknown as PropertiesDbClient
}

const TABLE = 'properties'
const BASE_MAP_PHOTOS_BUCKET = 'property-base-map-photos'

/** The four columns that together define a base map — always written as one set, never piecemeal (see `updateBaseMap`). Mirrors apps/web's `BaseMapUpdate`. */
export type BaseMapUpdate = Pick<
  PropertyInput,
  'baseMapSource' | 'baseMapPhotoPath' | 'baseMapDrawing' | 'scaleReference'
>

/**
 * Payload for `createWithBaseMap` — a Property built directly from a
 * photographed base map, with no address and no geocoding at all.
 * `id` is generated by the caller before this runs, so an already-uploaded
 * photo's storage path (written under it via `uploadBaseMapPhoto`) lines up
 * with the row it ends up belonging to. Mirrors apps/web's identical type,
 * minus `'drawn'`: drawing a base plan is desktop-only (ADR-0003).
 */
export interface PropertyCreateWithBaseMapInput {
  id: string
  name: string
  baseMapSource: 'photo'
  baseMapPhotoPath: string
  scaleReference: NonNullable<PropertyInput['scaleReference']>
}

async function requireUserId(client: PropertiesDbClient): Promise<string> {
  const { data, error } = await client.auth.getUser()
  if (error || !data.user) throw new Error('Not authenticated.')
  return data.user.id
}

export class PropertiesRepository {
  private readonly client: PropertiesDbClient

  constructor(client: PropertiesDbClient) {
    this.client = client
  }

  /** The account's one Property (MVP: at most one), or `null` if none exists yet. */
  async get(): Promise<Property | null> {
    const { data, error } = await this.client.from(TABLE).select('*').maybeSingle()
    if (error) throw new Error(error.message)
    return data ? propertyFromRow(data as PropertyRow) : null
  }

  /** A signed URL for a `'photo'` Property's base map — the bucket is private, so the Map screen can't just point an `<Image>` at the stored path. Mirrors apps/web's identical method. */
  async getBaseMapPhotoUrl(path: string): Promise<string> {
    const { data, error } = await this.client.storage
      .from(BASE_MAP_PHOTOS_BUCKET)
      .createSignedUrl(path, 3600)
    if (error || !data) throw new Error(error?.message ?? 'Could not sign photo URL.')
    return data.signedUrl
  }

  /**
   * Uploads a photographed plot plan/survey and returns its storage path —
   * the caller persists that path via `createWithBaseMap`/`updateBaseMap`.
   *
   * Takes a `PickedPhoto` rather than apps/web's `File`, which React Native
   * has no equivalent of: the picked image is read off its local `uri` into
   * an `ArrayBuffer` first, the same way `PlantsRepository.uploadReferencePhoto`
   * and `TagScanRepository.uploadTagPhoto` already do.
   *
   * The `<user_id>/...` path prefix isn't cosmetic — the bucket's RLS policy
   * (migration 0017) authorises an insert by matching the first path segment
   * against `auth.uid()`.
   */
  async uploadBaseMapPhoto(propertyId: string, photo: PickedPhoto): Promise<string> {
    const userId = await requireUserId(this.client)
    const path = `${userId}/${propertyId}/${Crypto.randomUUID()}-${photo.name}`
    const arrayBuffer = await fetch(photo.uri).then((res) => res.arrayBuffer())
    const { error } = await this.client.storage
      .from(BASE_MAP_PHOTOS_BUCKET)
      .upload(path, arrayBuffer, { contentType: photo.mimeType })
    if (error) throw new Error(error.message)
    return path
  }

  /**
   * Creates a Property directly from a photographed base map — the
   * privacy-motivated alternative to the address-driven aerial flow (see
   * CONTEXT.md's Property entry). No Edge Function, no geocoding, no Esri
   * call: unlike an aerial Property, this touches no external adapter, which
   * is why the phone can do it at all without either function being ported.
   */
  async createWithBaseMap(input: PropertyCreateWithBaseMapInput): Promise<Property> {
    const userId = await requireUserId(this.client)
    const { data, error } = await this.client
      .from(TABLE)
      .insert({
        id: input.id,
        user_id: userId,
        name: input.name,
        address: null,
        resolved_address: null,
        latitude: null,
        longitude: null,
        imagery_zoom: null,
        imagery_available: false,
        base_map_source: input.baseMapSource,
        base_map_photo_path: input.baseMapPhotoPath,
        // Always null, not a caller's choice: drawing a base plan is
        // desktop-only (ADR-0003), and the check constraint in migration 0017
        // rejects a 'photo' row that carries a drawing anyway.
        base_map_drawing: null,
        scale_reference: input.scaleReference,
      })
      .select()
      .single()
    if (error) {
      const message = error.code === '23505' ? 'You already have a Property.' : error.message
      throw new Error(message)
    }
    return propertyFromRow(data as PropertyRow)
  }

  /**
   * Frees the account's one-Property slot (MVP has no edit — delete and
   * re-create instead). Mirrors apps/web's identical method.
   *
   * At parity per ADR-0003, and not optional now that the phone can *create*
   * a Property: without this, a plan photographed on the phone could only be
   * undone from the desktop, which is exactly the dead end #5's own QA hit
   * before web grew this control.
   *
   * The Beds and Plantings underneath go with it, via the FK cascade.
   */
  async remove(id: string): Promise<void> {
    const { error } = await this.client.from(TABLE).delete().eq('id', id)
    if (error) throw new Error(error.message)
  }

  /**
   * Switches a Property to a photographed base map with the Scale Reference
   * that calibrates it — the fallback for an aerial Property whose address
   * turned out to have no imagery coverage.
   *
   * All four columns go in one write on purpose: the
   * `properties_base_map_source_consistent` check constraint (migration 0017)
   * rejects a row whose source and its supporting columns disagree, so a
   * photo path saved ahead of its scale reference wouldn't merely look
   * half-configured, it would be refused outright.
   */
  async updateBaseMap(id: string, update: BaseMapUpdate): Promise<Property> {
    const { data, error } = await this.client
      .from(TABLE)
      .update({
        base_map_source: update.baseMapSource,
        base_map_photo_path: update.baseMapPhotoPath,
        base_map_drawing: update.baseMapDrawing,
        scale_reference: update.scaleReference,
      })
      .eq('id', id)
      .select()
      .single()
    if (error) throw new Error(error.message)
    return propertyFromRow(data as PropertyRow)
  }
}
